# Generated by Django 4.0.5 on 2022-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photopost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='caption_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
